### ISSUE TITLE
Using Result<_,Error> instead of assert/assert_eq in code

### ISSUE THREAD

**Issue by pvichivanives** [d0rianb/rtf-parser#3]
Hi! Can we swap from using the assert_eq/asserts to an assert system where the errors can be handled?

This would be very useful since most of the time we would not want the entire program to panic upon finding an invalid RTF string/file.

**Comment by d0rianb** [comment]
Thanks for this issue, should be fixed with 06cf51d0244742bbdf08a728fb1b7ed79b8a06c0.

**Comment by pvichivanives** [comment]
Thanks!
