### ISSUE TITLE
Getting IgnorableDestinationParsingError, likely from parse_ignore_groups off by 1

### ISSUE THREAD

**Issue by pvichivanives** [d0rianb/rtf-parser#5]
The example rtf file found here: https://jeroen.github.io/files/sample.rtf fails the parser with an IgnorableDestinationParsingError. I believe this isn't expected behavior since parse_ignore_groups should remove all of them.

![image](https://github.com/d0rianb/rtf-parser/assets/141073394/3eb8661c-4f48-47b0-96e3-79c6c2c4976a)
It seems like rtf text like above could have caused it because there are two ignorable destinations adjacent to each other.

I've open a pull request here: https://github.com/d0rianb/rtf-parser/pull/4 with what I think should fix it.

**Comment by d0rianb** [comment]
Fixed in #4
